import type { Metadata } from "next";
import Link from "next/link";
import './global.css'
import styles from './styles.module.css'

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <nav><Link href="/"><img src="/vervoerregio_amsterdam_logo.svg" alt="" /></Link></nav>
        {children}
        </body>
    </html>
  );
}
